date.timezone=UTC
display_errors=Off
log_errors=On

; Maximum amount of memory a script may consume
; http://php.net/memory-limit
memory_limit = 1G

; Maximum allowed size for uploaded files.
; http://php.net/upload-max-filesize
upload_max_filesize = 500M

; Sets max size of post data allowed.
; http://php.net/post-max-size
post_max_size = 500M

; Maximum execution time of each script, in seconds
max_execution_time = 300

; Maximum amount of time each script may spend parsing request data
max_input_time = 300

; How many GET/POST/COOKIE input variables may be accepted
max_input_vars = 3000

; Default socket timeout
default_socket_timeout = 300

; Request terminate timeout for FPM
request_terminate_timeout = 300

; Maximum number of files that can be uploaded via a single request
max_file_uploads = 20

; Whether to allow HTTP file uploads
file_uploads = On

; Temporary directory for HTTP uploaded files
upload_tmp_dir = /tmp
